# Generated by Django 4.2.20 on 2025-04-07 05:01

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(
                default='+0000000000',
                max_length=15,
                validators=[django.core.validators.RegexValidator(
                    regex=r'^\+?1?\d{9,15}$',
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
                )]
            ),
        ),
    ]
